---
name: "Setup Go Workspace"
description: "Configure Go and prepare the workspace"

runs:
  using: composite
  steps:
    - name: Set up Golang
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Install Just
      uses: extractions/setup-just@v2

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev

    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry
          ~/.cargo/git
          target/
        key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-${{ runner.os }}-

    - name: Build project
      shell: bash
      run: |
        cargo build --verbose
