---
# Aeternum API pre-commit configuration

fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/AndrejOrsula/pre-commit-cargo
    rev: 0.4.0
    hooks:
      - id: cargo-fmt
      - id: cargo-update
      - id: cargo-clippy
        args: ["--all-targets", "--all-features"]
      - id: cargo-check
        args: ["--all-targets", "--all-features"]
      - id: cargo-fix
        args: ["--allow-dirty", "--allow-staged"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    # Otherwise will fail on commit-msg hook
    hooks:
      - id: prettier
        files: ^.*\.(go|json|yaml|yml)$

  - repo: https://github.com/codespell-project/codespell.git
    rev: v2.2.6
    hooks:
      - id: codespell
        args: [-w]
        files: ^.*\.(md|go|jinja|yaml|yml|sh)$
