[package]
name = "gitrusty"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.18"
clap = { version = "4.4", features = ["derive"] }
ratatui = "0.26"
crossterm = "0.27"
colored = "2.1"

[dev-dependencies]
tempfile = "3.9"
