---
name: Project Build CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run setup
        uses: ./.github/actions/setup-workspace

      - name: Run tests
        run: |
          cargo test --verbose
